# Generated by Django 5.2.17 on 2026-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="full name"),
                ),
                (
                    "designation",
                    models.CharField(max_length=100, verbose_name="designation"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="chefs/", verbose_name="photo"
                    ),
                ),
                ("biography", models.TextField(blank=True, verbose_name="biography")),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="experience, years"
                    ),
                ),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="show on the site"),
                ),
            ],
            options={
                "verbose_name": "chef",
                "verbose_name_plural": "chefs",
                "ordering": ["order", "full_name"],
            },
        ),
    ]
