# Generated by Django 5.2.17 on 2026-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "office_address",
                    models.CharField(max_length=250, verbose_name="office address"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(max_length=30, verbose_name="phone")),
                (
                    "working_hours_weekdays",
                    models.CharField(
                        blank=True,
                        default="09:00 - 19:00",
                        max_length=100,
                        verbose_name="working hours on weekdays",
                    ),
                ),
                (
                    "working_hours_weekend",
                    models.CharField(
                        blank=True,
                        default="10:00 - 17:00",
                        max_length=100,
                        verbose_name="working hours on weekend",
                    ),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter")),
                (
                    "map_embed",
                    models.TextField(blank=True, verbose_name="map embed code"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="primary contact"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "contact information",
                "verbose_name_plural": "contact information",
            },
        ),
    ]
