# Generated by Django 5.2.17 on 2026-09-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=150, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('is_processed', models.BooleanField(default=False, verbose_name='processed')),
            ],
            options={
                'verbose_name': 'message from the form',
                'verbose_name_plural': 'messages from the form',
                'ordering': ['-created_at'],
            },
        ),
    ]
