# Generated by Django 5.2.17 on 2026-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="service title"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="for example, bi bi-cake",
                        max_length=50,
                        verbose_name="icon css class",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="services/", verbose_name="image"
                    ),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="price from",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="show on the site"),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ["order", "title"],
            },
        ),
    ]
