# Generated by Django 5.2.17 on 2026-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="CakeZone", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "slogan",
                    models.CharField(blank=True, max_length=200, verbose_name="slogan"),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="short description"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="establishment/", verbose_name="photo"
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="years of experience"
                    ),
                ),
                (
                    "cakes_baked",
                    models.PositiveIntegerField(default=0, verbose_name="cakes baked"),
                ),
                (
                    "happy_clients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="happy clients"
                    ),
                ),
                (
                    "master_chefs",
                    models.PositiveIntegerField(default=0, verbose_name="master chefs"),
                ),
                (
                    "awards",
                    models.PositiveIntegerField(default=0, verbose_name="awards"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="show on the site"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "establishment",
                "verbose_name_plural": "establishment",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=100, verbose_name="client name"),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="profession"
                    ),
                ),
                ("text", models.TextField(verbose_name="testimonial text")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="testimonials/",
                        verbose_name="client photo",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=5, verbose_name="rating"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="published"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "testimonial",
                "verbose_name_plural": "testimonials",
                "ordering": ["-created_at"],
            },
        ),
    ]
