# Generated by Django 5.2.17 on 2026-09-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="description"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="show on the site"),
                ),
            ],
            options={
                "verbose_name": "dish category",
                "verbose_name_plural": "dish categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="price"
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="weight, g"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="dishes/", verbose_name="photo"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="in stock"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="menu.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "dish",
                "verbose_name_plural": "dishes",
                "ordering": ["category", "name"],
            },
        ),
    ]
